version: '3.3'

services:

  junior-java-backend-assignment:
    build:
      context: '.'
    ports:
      - '8080:8080/tcp'

  database:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dockerdb'
      - 'POSTGRES_USER=assignment'
      - 'POSTGRES_PASSWORD=abc123'
    volumes:
      - './database:/docker-entrypoint-initdb.d'
    ports:
      - '5432:5432/tcp'
